from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateProduct(object):
    def setupUi(self, CreateProduct):
        CreateProduct.setObjectName("CreateProduct")
        CreateProduct.resize(527, 390)
        self.label_6 = QtWidgets.QLabel(CreateProduct)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 531, 401))
        self.label_6.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.512, y1:0, x2:0.532, y2:1, stop:0.174129 rgba(36, 214, 202), stop:1 rgba(255, 255, 255, 255));")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(CreateProduct)
        self.label_7.setGeometry(QtCore.QRect(50, 260, 181, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(CreateProduct)
        self.label_8.setGeometry(QtCore.QRect(50, 220, 141, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.input_precio_costo = QtWidgets.QLineEdit(CreateProduct)
        self.input_precio_costo.setGeometry(QtCore.QRect(280, 220, 205, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input_precio_costo.setFont(font)
        self.input_precio_costo.setObjectName("input_precio_costo")
        self.input_precio_publico = QtWidgets.QLineEdit(CreateProduct)
        self.input_precio_publico.setGeometry(QtCore.QRect(280, 260, 205, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input_precio_publico.setFont(font)
        self.input_precio_publico.setObjectName("input_precio_publico")
        self.label_2 = QtWidgets.QLabel(CreateProduct)
        self.label_2.setGeometry(QtCore.QRect(51, 68, 76, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.input_cod = QtWidgets.QLineEdit(CreateProduct)
        self.input_cod.setGeometry(QtCore.QRect(280, 68, 205, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input_cod.setFont(font)
        self.input_cod.setObjectName("input_cod")
        self.label = QtWidgets.QLabel(CreateProduct)
        self.label.setGeometry(QtCore.QRect(50, 10, 364, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(CreateProduct)
        self.label_3.setGeometry(QtCore.QRect(51, 105, 151, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.input_name = QtWidgets.QLineEdit(CreateProduct)
        self.input_name.setGeometry(QtCore.QRect(280, 105, 205, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input_name.setFont(font)
        self.input_name.setObjectName("input_name")
        self.label_4 = QtWidgets.QLabel(CreateProduct)
        self.label_4.setGeometry(QtCore.QRect(51, 142, 221, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.input_price = QtWidgets.QLineEdit(CreateProduct)
        self.input_price.setGeometry(QtCore.QRect(280, 142, 205, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input_price.setFont(font)
        self.input_price.setObjectName("input_price")
        self.label_5 = QtWidgets.QLabel(CreateProduct)
        self.label_5.setGeometry(QtCore.QRect(51, 179, 141, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.input_category = QtWidgets.QLineEdit(CreateProduct)
        self.input_category.setGeometry(QtCore.QRect(280, 179, 205, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input_category.setFont(font)
        self.input_category.setObjectName("input_category")
        self.btn_create = QtWidgets.QPushButton(CreateProduct)
        self.btn_create.setGeometry(QtCore.QRect(200, 340, 93, 33))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_create.setFont(font)
        self.btn_create.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_create.setObjectName("btn_create")
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.input_precio_costo.raise_()
        self.input_precio_publico.raise_()

        self.retranslateUi(CreateProduct)
        QtCore.QMetaObject.connectSlotsByName(CreateProduct)

    def retranslateUi(self, CreateProduct):
        _translate = QtCore.QCoreApplication.translate
        CreateProduct.setWindowTitle(_translate("CreateProduct", "Form"))
        self.label_7.setText(_translate("CreateProduct", "Precio(publico)"))
        self.label_8.setText(_translate("CreateProduct", "Precio(costo)"))
        self.input_precio_costo.setPlaceholderText(_translate("CreateProduct", "Costo"))
        self.input_precio_publico.setPlaceholderText(_translate("CreateProduct", "Publico"))
        self.label_2.setText(_translate("CreateProduct", "Codigo:"))
        self.input_cod.setPlaceholderText(_translate("CreateProduct", "codigo"))
        self.label.setText(_translate("CreateProduct", "Crear Nuevo Producto"))
        self.label_3.setText(_translate("CreateProduct", "Describcion :"))
        self.input_name.setPlaceholderText(_translate("CreateProduct", "nombre"))
        self.label_4.setText(_translate("CreateProduct", "CODMEDIDAINV: "))
        self.input_price.setPlaceholderText(_translate("CreateProduct", "precio"))
        self.label_5.setText(_translate("CreateProduct", "Existencias: "))
        self.input_category.setPlaceholderText(_translate("CreateProduct", "categoria"))
        self.btn_create.setText(_translate("CreateProduct", "Crear"))
